server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esta línea es la magia que permite a React manejar las rutas internamente
        try_files $uri $uri/ /index.html;
    }

    # Manejo de errores básicos
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}