server.port=8082
spring.datasource.url=jdbc:postgresql://postgres-db:5432/despachos_ventas_db
spring.datasource.username=admin
spring.datasource.password=SecurePassword123!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
