name: CI Pipeline - Full Stack

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop, feature/* ]

jobs:
  # --- JOB PARA BACKEND (Maven) ---
  backend-checks:
    strategy:
      matrix:
        microservice: [ back-Despachos_SpringBoot, back-Ventas_SpringBoot ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilar y Testear
        run: |
          cd ${{ matrix.microservice }}
          # Agregamos skipTests por si no tienes tests configurados, igual que tu compañero
          mvn clean package -Dmaven.test.skip=true -B
        shell: bash

  # --- JOB PARA FRONTEND (Node) ---
  frontend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front_despacho
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: front_despacho/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Construir aplicación
