name: Deploy a AWS ECR y ECS

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Asegúrate de que estos nombres coincidan con tus carpetas reales
        service: [front_despacho, back-Despachos_SpringBoot, back-Ventas_SpringBoot]
    steps:
      - uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Construir y subir imagen
        run: |
          cd ${{ matrix.service }}
          docker build -t devops-${{ matrix.service }}:latest .
          docker tag devops-${{ matrix.service }}:latest ${{ steps.login-ecr.outputs.registry }}/devops-${{ matrix.service }}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/devops-${{ matrix.service }}:latest